### ISSUE TITLE
setting

### ISSUE THREAD

**Issue by huang123ying** [zhyhan/RDA#2]
where can i use the PMD,the get_proxy_loss in MMD.py? but the train.py uses the get_gradual_loss in ours.py.And how can i get the proxy distribution? thanks

**Comment by zhyhan** [comment]
Thanks for your valuable question, we will update the name of the corresponding functions to make you understand the meaning explicitly.

**Comment by huang123ying** [comment]
I understand the meaning now, please let me know if you update the name of the corresponding functions.thanks!
